name: Development Workflow
on: [push]
jobs:
  deploy_stage:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy To Staging
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_PRIVATE }}
          script: |
            cd ${{ secrets.PROJECT_PATH }}
            git pull
            composer update --no-progress --ignore-platform-reqs
            composer dump-autoload
            git status
